name: nayuta_sensors
description: Flutter plugin for accessing accelerometer and gyroscope sensors.
version: 1.0.0
homepage: https://github.com/Nayuta403/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.sensors
        pluginClass: SensorsPlugin
      ios:
        pluginClass: FLTSensorsPlusPlugin
      web:
        default_package: sensors_plus_web

dependencies:
  flutter:
    sdk: flutter
  sensors_plus_web: ^1.0.0
  sensors_plus_platform_interface: ^1.0.0

dev_dependencies:
  test: ^1.16.4
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
